# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User_Interface1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(782, 593)
        MainWindow.setStyleSheet("*{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    background:none;\n"
"    padding:0;\n"
"    margin:0;\n"
"    color:#E5D9D9;\n"
"}\n"
"\n"
"#centralwidget{\n"
"    background-color:#2C313C;\n"
"    \n"
"}\n"
"\n"
"#leftMenuSubContainer{\n"
"    background-color:#1B1E23;\n"
"\n"
"}\n"
"\n"
"#leftMenuSubContainer QPushButton{\n"
"    text-align:left;\n"
"    padding:2px 30px;\n"
"    border-top-left-radius:8px;\n"
"    border-top-right-radius:8px;    \n"
"    border-bottom-left-radius:8px;\n"
"    border-bottom-right-radius:8px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenuContainer = QtWidgets.QWidget(self.centralwidget)
        self.leftMenuContainer.setMinimumSize(QtCore.QSize(170, 0))
        self.leftMenuContainer.setObjectName("leftMenuContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftMenuContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.leftMenuSubContainer = QtWidgets.QWidget(self.leftMenuContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftMenuSubContainer.sizePolicy().hasHeightForWidth())
        self.leftMenuSubContainer.setSizePolicy(sizePolicy)
        self.leftMenuSubContainer.setMinimumSize(QtCore.QSize(170, 0))
        self.leftMenuSubContainer.setMaximumSize(QtCore.QSize(128, 16777215))
        self.leftMenuSubContainer.setObjectName("leftMenuSubContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenuSubContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sideMenuFrame1 = QtWidgets.QFrame(self.leftMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sideMenuFrame1.sizePolicy().hasHeightForWidth())
        self.sideMenuFrame1.setSizePolicy(sizePolicy)
        self.sideMenuFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideMenuFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideMenuFrame1.setObjectName("sideMenuFrame1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.sideMenuFrame1)
        self.horizontalLayout_2.setContentsMargins(10, 16, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuButton = QtWidgets.QPushButton(self.sideMenuFrame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuButton.sizePolicy().hasHeightForWidth())
        self.menuButton.setSizePolicy(sizePolicy)
        self.menuButton.setMinimumSize(QtCore.QSize(150, 35))
        self.menuButton.setStyleSheet("background-color:rgb(45, 50, 61)\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons2/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuButton.setIcon(icon)
        self.menuButton.setIconSize(QtCore.QSize(16, 16))
        self.menuButton.setAutoRepeatDelay(300)
        self.menuButton.setObjectName("menuButton")
        self.horizontalLayout_2.addWidget(self.menuButton)
        self.verticalLayout_2.addWidget(self.sideMenuFrame1, 0, QtCore.Qt.AlignTop)
        self.sideMenuFrame2 = QtWidgets.QFrame(self.leftMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sideMenuFrame2.sizePolicy().hasHeightForWidth())
        self.sideMenuFrame2.setSizePolicy(sizePolicy)
        self.sideMenuFrame2.setMinimumSize(QtCore.QSize(170, 0))
        self.sideMenuFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideMenuFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideMenuFrame2.setObjectName("sideMenuFrame2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sideMenuFrame2)
        self.verticalLayout_3.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_3.setSpacing(25)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeButton = QtWidgets.QPushButton(self.sideMenuFrame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeButton.sizePolicy().hasHeightForWidth())
        self.homeButton.setSizePolicy(sizePolicy)
        self.homeButton.setMinimumSize(QtCore.QSize(170, 40))
        self.homeButton.setStyleSheet("background-color:rgb(44, 49, 60)")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons2/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon1)
        self.homeButton.setObjectName("homeButton")
        self.verticalLayout_3.addWidget(self.homeButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gestureLibraryButton = QtWidgets.QPushButton(self.sideMenuFrame2)
        self.gestureLibraryButton.setMinimumSize(QtCore.QSize(160, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons2/globe.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gestureLibraryButton.setIcon(icon2)
        self.gestureLibraryButton.setObjectName("gestureLibraryButton")
        self.verticalLayout_3.addWidget(self.gestureLibraryButton)
        self.manualButton = QtWidgets.QPushButton(self.sideMenuFrame2)
        self.manualButton.setMinimumSize(QtCore.QSize(150, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons2/book-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manualButton.setIcon(icon3)
        self.manualButton.setObjectName("manualButton")
        self.verticalLayout_3.addWidget(self.manualButton)
        self.verticalLayout_2.addWidget(self.sideMenuFrame2, 0, QtCore.Qt.AlignTop)
        self.frame_7 = QtWidgets.QFrame(self.leftMenuSubContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_7, 0, QtCore.Qt.AlignVCenter)
        self.sideMenuFrame3 = QtWidgets.QFrame(self.leftMenuSubContainer)
        self.sideMenuFrame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideMenuFrame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sideMenuFrame3.setObjectName("sideMenuFrame3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.sideMenuFrame3)
        self.verticalLayout_4.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.informationButton = QtWidgets.QPushButton(self.sideMenuFrame3)
        self.informationButton.setMinimumSize(QtCore.QSize(150, 40))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons2/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.informationButton.setIcon(icon4)
        self.informationButton.setObjectName("informationButton")
        self.verticalLayout_4.addWidget(self.informationButton)
        self.settingsButton = QtWidgets.QPushButton(self.sideMenuFrame3)
        self.settingsButton.setMinimumSize(QtCore.QSize(150, 40))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons2/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon5)
        self.settingsButton.setObjectName("settingsButton")
        self.verticalLayout_4.addWidget(self.settingsButton)
        self.verticalLayout_2.addWidget(self.sideMenuFrame3, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.leftMenuSubContainer, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.leftMenuContainer, 0, QtCore.Qt.AlignLeft)
        self.mainBodyContainer = QtWidgets.QWidget(self.centralwidget)
        self.mainBodyContainer.setMinimumSize(QtCore.QSize(500, 0))
        self.mainBodyContainer.setMaximumSize(QtCore.QSize(167772, 16777215))
        self.mainBodyContainer.setStyleSheet("background-color:rgb(44, 49, 60);\n"
"text-align:center;")
        self.mainBodyContainer.setObjectName("mainBodyContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mainBodyContainer)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.titleContainer = QtWidgets.QFrame(self.mainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleContainer.sizePolicy().hasHeightForWidth())
        self.titleContainer.setSizePolicy(sizePolicy)
        self.titleContainer.setMinimumSize(QtCore.QSize(450, 50))
        self.titleContainer.setMaximumSize(QtCore.QSize(16777215, 50))
        self.titleContainer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titleContainer.setStyleSheet("background-color:#343B48;\n"
"border-top-left-radius:8px;\n"
"    border-top-right-radius:8px;    \n"
"    border-bottom-left-radius:8px;\n"
"    border-bottom-right-radius:8px;")
        self.titleContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleContainer.setObjectName("titleContainer")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.titleContainer)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.titleText = QtWidgets.QTextEdit(self.titleContainer)
        self.titleText.setStyleSheet("color:#5479C4")
        self.titleText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.titleText.setObjectName("titleText")
        self.horizontalLayout_4.addWidget(self.titleText)
        self.frame_6 = QtWidgets.QFrame(self.titleContainer)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        self.pushButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icons2/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon6)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_2.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Icons2/minimize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon7)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_3.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Icons2/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon8)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.verticalLayout_5.addWidget(self.titleContainer, 0, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.mainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_11.setContentsMargins(-1, 50, 15, 30)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.startButtonContainer = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButtonContainer.sizePolicy().hasHeightForWidth())
        self.startButtonContainer.setSizePolicy(sizePolicy)
        self.startButtonContainer.setMaximumSize(QtCore.QSize(1000, 1000))
        self.startButtonContainer.setStyleSheet("#startButtonContainer {\n"
"    border: 1px solid #AA1465;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"#startButton{\n"
"    text-align:left;\n"
"    padding:2px 30px;\n"
"    border-top-left-radius:8px;\n"
"    border-top-right-radius:8px;    \n"
"    border-bottom-left-radius:8px;\n"
"    border-bottom-right-radius:8px;\n"
"}")
        self.startButtonContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.startButtonContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.startButtonContainer.setObjectName("startButtonContainer")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.startButtonContainer)
        self.verticalLayout_7.setContentsMargins(60, 15, 60, 15)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.startButtonContainer)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.startButton = QtWidgets.QPushButton(self.startButtonContainer)
        self.startButton.setStyleSheet("background-color:rgb(170, 20, 101);\n"
"text-align:center;\n"
"\n"
"")
        self.startButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Icons2/power.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon9)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_7.addWidget(self.startButton)
        self.verticalLayout_11.addWidget(self.startButtonContainer, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_5.addWidget(self.frame)
        self.subMainBodyContainer = QtWidgets.QFrame(self.mainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subMainBodyContainer.sizePolicy().hasHeightForWidth())
        self.subMainBodyContainer.setSizePolicy(sizePolicy)
        self.subMainBodyContainer.setStyleSheet("#resetFirstFrameButton{\n"
"    border: 1px solid #568AF2;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"#minimizeToTrayButton{\n"
"    border: 1px solid #568AF2;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QPushButton {\n"
"    color: :#5479C4; /* Change this to your desired text color */\n"
"  \n"
"}")
        self.subMainBodyContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subMainBodyContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subMainBodyContainer.setObjectName("subMainBodyContainer")
        self.gridLayout = QtWidgets.QGridLayout(self.subMainBodyContainer)
        self.gridLayout.setVerticalSpacing(30)
        self.gridLayout.setObjectName("gridLayout")
        self.modeContainer = QtWidgets.QFrame(self.subMainBodyContainer)
        self.modeContainer.setStyleSheet("#modeContainer {\n"
"    border: 1px solid #568AF2;\n"
"    border-radius: 8px; \n"
"}")
        self.modeContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.modeContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.modeContainer.setObjectName("modeContainer")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.modeContainer)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_2 = QtWidgets.QFrame(self.modeContainer)
        self.frame_2.setStyleSheet("#SelectMode{\n"
"    color:#568AF2;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.SelectMode = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelectMode.sizePolicy().hasHeightForWidth())
        self.SelectMode.setSizePolicy(sizePolicy)
        self.SelectMode.setObjectName("SelectMode")
        self.verticalLayout_6.addWidget(self.SelectMode, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_12.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_12.addWidget(self.checkBox)
        self.verticalLayout_6.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.modeContainer, 0, 0, 1, 1)
        self.minimizeToTrayButton = QtWidgets.QPushButton(self.subMainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimizeToTrayButton.sizePolicy().hasHeightForWidth())
        self.minimizeToTrayButton.setSizePolicy(sizePolicy)
        self.minimizeToTrayButton.setMinimumSize(QtCore.QSize(0, 50))
        self.minimizeToTrayButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.minimizeToTrayButton.setStyleSheet("color:#5479C4\n"
"\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/Icons2/chevrons-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeToTrayButton.setIcon(icon10)
        self.minimizeToTrayButton.setObjectName("minimizeToTrayButton")
        self.gridLayout.addWidget(self.minimizeToTrayButton, 1, 1, 1, 1, QtCore.Qt.AlignTop)
        self.feedbackContainer = QtWidgets.QFrame(self.subMainBodyContainer)
        self.feedbackContainer.setStyleSheet("#feedbackContainer {\n"
"    border: 1px solid #568AF2;\n"
"    border-radius: 8px; \n"
" \n"
"    \n"
"}")
        self.feedbackContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.feedbackContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.feedbackContainer.setObjectName("feedbackContainer")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.feedbackContainer)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_3 = QtWidgets.QFrame(self.feedbackContainer)
        self.frame_3.setStyleSheet("#FeebackGesture{\n"
"    color:#568AF2;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.FeedbackGesture = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FeedbackGesture.sizePolicy().hasHeightForWidth())
        self.FeedbackGesture.setSizePolicy(sizePolicy)
        self.FeedbackGesture.setStyleSheet("")
        self.FeedbackGesture.setObjectName("FeedbackGesture")
        self.verticalLayout_10.addWidget(self.FeedbackGesture, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_13.addWidget(self.checkBox_4)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_13.addWidget(self.checkBox_3)
        self.verticalLayout_10.addWidget(self.frame_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout_9.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.feedbackContainer, 0, 1, 1, 1)
        self.resetFirstFrameButton = QtWidgets.QPushButton(self.subMainBodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetFirstFrameButton.sizePolicy().hasHeightForWidth())
        self.resetFirstFrameButton.setSizePolicy(sizePolicy)
        self.resetFirstFrameButton.setMinimumSize(QtCore.QSize(5, 50))
        self.resetFirstFrameButton.setMaximumSize(QtCore.QSize(16777215, 60))
        self.resetFirstFrameButton.setStyleSheet("color:#5479C4")
        self.resetFirstFrameButton.setObjectName("resetFirstFrameButton")
        self.gridLayout.addWidget(self.resetFirstFrameButton, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.verticalLayout_5.addWidget(self.subMainBodyContainer)
        self.frame.raise_()
        self.titleContainer.raise_()
        self.subMainBodyContainer.raise_()
        self.horizontalLayout.addWidget(self.mainBodyContainer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuButton.setToolTip(_translate("MainWindow", "Menu"))
        self.menuButton.setText(_translate("MainWindow", "Menu"))
        self.homeButton.setToolTip(_translate("MainWindow", "Home"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.gestureLibraryButton.setToolTip(_translate("MainWindow", "Gesture Library"))
        self.gestureLibraryButton.setText(_translate("MainWindow", "Gesture Library"))
        self.manualButton.setToolTip(_translate("MainWindow", "Learn how to use the app"))
        self.manualButton.setText(_translate("MainWindow", "Manual"))
        self.informationButton.setToolTip(_translate("MainWindow", "Information about the app"))
        self.informationButton.setText(_translate("MainWindow", "Information"))
        self.settingsButton.setToolTip(_translate("MainWindow", "Go to settings"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.titleText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700; font-style:italic;\">MotionPilot</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Start Application"))
        self.SelectMode.setText(_translate("MainWindow", "Select Mode"))
        self.checkBox_2.setText(_translate("MainWindow", "Manual Mode"))
        self.checkBox.setText(_translate("MainWindow", "Auto Mode"))
        self.minimizeToTrayButton.setText(_translate("MainWindow", "Minimize to tray"))
        self.FeedbackGesture.setText(_translate("MainWindow", "Feedback Gesture"))
        self.checkBox_4.setText(_translate("MainWindow", "Off"))
        self.checkBox_3.setText(_translate("MainWindow", "On"))
        self.resetFirstFrameButton.setText(_translate("MainWindow", "Reset First Frame"))
import Resources_rc
