# Form implementation generated from reading ui file 'UI_v3_Responsive.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 500)
        MainWindow.setMaximumSize(QtCore.QSize(1440, 1024))
        MainWindow.setStyleSheet("*{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    background:none;\n"
"    padding:0;\n"
"    margin:0;\n"
"    color:#E5D9D9;\n"
"}\n"
"\n"
"\n"
"#centralwidget{\n"
"    background-color:#2C313C;\n"
"    \n"
"}\n"
"\n"
"#Menu_Widget{\n"
"    background-color:#1B1E23;\n"
"border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;    \n"
"    border-bottom-left-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"\n"
"}\n"
"\n"
"#More_Menu_Widget{\n"
"    background-color: #1F2127;\n"
"border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;    \n"
"    border-bottom-left-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"#Menu_Widget QPushButton{\n"
"    text-align:left;\n"
"    padding:2px 10px;\n"
"    border-top-left-radius:8px;\n"
"    border-top-right-radius:8px;    \n"
"    border-bottom-left-radius:8px;\n"
"    border-bottom-right-radius:8px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Menu_Widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.Menu_Widget.setMinimumSize(QtCore.QSize(150, 450))
        self.Menu_Widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.Menu_Widget.setStyleSheet("QPushButton:checked{\n"
"    background-color:rgb(44, 49, 60)\n"
"}")
        self.Menu_Widget.setObjectName("Menu_Widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Menu_Widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Menu_Top_Frame = QtWidgets.QFrame(parent=self.Menu_Widget)
        self.Menu_Top_Frame.setMaximumSize(QtCore.QSize(16777215, 55))
        self.Menu_Top_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Menu_Top_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Menu_Top_Frame.setObjectName("Menu_Top_Frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Menu_Top_Frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Menu_Button = QtWidgets.QPushButton(parent=self.Menu_Top_Frame)
        self.Menu_Button.setMinimumSize(QtCore.QSize(0, 35))
        self.Menu_Button.setStyleSheet("\n"
"padding:2px 30px;\n"
"background-color: rgb(45, 50, 61);\n"
"    border-radius: 8px; ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons2/menu.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Menu_Button.setIcon(icon)
        self.Menu_Button.setObjectName("Menu_Button")
        self.horizontalLayout_4.addWidget(self.Menu_Button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_4.addWidget(self.Menu_Top_Frame)
        self.Menu_Middle_Frame = QtWidgets.QFrame(parent=self.Menu_Widget)
        self.Menu_Middle_Frame.setMinimumSize(QtCore.QSize(150, 300))
        self.Menu_Middle_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Menu_Middle_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Menu_Middle_Frame.setObjectName("Menu_Middle_Frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Menu_Middle_Frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Home_Button = QtWidgets.QPushButton(parent=self.Menu_Middle_Frame)
        self.Home_Button.setMinimumSize(QtCore.QSize(120, 35))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons2/home.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Home_Button.setIcon(icon1)
        self.Home_Button.setCheckable(True)
        self.Home_Button.setAutoExclusive(True)
        self.Home_Button.setObjectName("Home_Button")
        self.verticalLayout_5.addWidget(self.Home_Button)
        self.Library_Button = QtWidgets.QPushButton(parent=self.Menu_Middle_Frame)
        self.Library_Button.setMinimumSize(QtCore.QSize(120, 35))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons2/globe.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Library_Button.setIcon(icon2)
        self.Library_Button.setCheckable(True)
        self.Library_Button.setAutoExclusive(True)
        self.Library_Button.setObjectName("Library_Button")
        self.verticalLayout_5.addWidget(self.Library_Button)
        self.frame_3 = QtWidgets.QFrame(parent=self.Menu_Middle_Frame)
        self.frame_3.setMinimumSize(QtCore.QSize(140, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setContentsMargins(35, 0, -1, -1)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton.setStyleSheet("checked:{background-color: rgb(255, 255, 255);}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons2/cast.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 35))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons2/thumbs-up.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setAutoExclusive(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_7.addWidget(self.pushButton_2)
        self.verticalLayout_5.addWidget(self.frame_3, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.Manual_Button = QtWidgets.QPushButton(parent=self.Menu_Middle_Frame)
        self.Manual_Button.setMinimumSize(QtCore.QSize(120, 35))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Icons2/book-open.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Manual_Button.setIcon(icon5)
        self.Manual_Button.setCheckable(True)
        self.Manual_Button.setAutoExclusive(True)
        self.Manual_Button.setObjectName("Manual_Button")
        self.verticalLayout_5.addWidget(self.Manual_Button)
        self.frame_4 = QtWidgets.QFrame(parent=self.Menu_Middle_Frame)
        self.frame_4.setMinimumSize(QtCore.QSize(140, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_9.setContentsMargins(35, 0, -1, 6)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 35))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Icons2/refresh-ccw.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon6)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setAutoExclusive(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_9.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 35))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/Icons2/tool.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon7)
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setAutoExclusive(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_9.addWidget(self.pushButton_4)
        self.verticalLayout_5.addWidget(self.frame_4, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addWidget(self.Menu_Middle_Frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_4.addItem(spacerItem)
        self.Menu_Bottom_Frame = QtWidgets.QFrame(parent=self.Menu_Widget)
        self.Menu_Bottom_Frame.setMinimumSize(QtCore.QSize(150, 100))
        self.Menu_Bottom_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Menu_Bottom_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Menu_Bottom_Frame.setObjectName("Menu_Bottom_Frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Menu_Bottom_Frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Information_Button = QtWidgets.QPushButton(parent=self.Menu_Bottom_Frame)
        self.Information_Button.setMinimumSize(QtCore.QSize(120, 35))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/Icons2/info.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Information_Button.setIcon(icon8)
        self.Information_Button.setCheckable(True)
        self.Information_Button.setAutoExclusive(True)
        self.Information_Button.setObjectName("Information_Button")
        self.verticalLayout_6.addWidget(self.Information_Button)
        self.Settings_Button = QtWidgets.QPushButton(parent=self.Menu_Bottom_Frame)
        self.Settings_Button.setMinimumSize(QtCore.QSize(120, 35))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/Icons2/settings.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Settings_Button.setIcon(icon9)
        self.Settings_Button.setCheckable(True)
        self.Settings_Button.setAutoExclusive(True)
        self.Settings_Button.setObjectName("Settings_Button")
        self.verticalLayout_6.addWidget(self.Settings_Button)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addWidget(self.Menu_Bottom_Frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout.addWidget(self.Menu_Widget)
        self.More_Menu_Widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.More_Menu_Widget.setMinimumSize(QtCore.QSize(150, 450))
        self.More_Menu_Widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.More_Menu_Widget.setStyleSheet("background-color: #1F2127;")
        self.More_Menu_Widget.setObjectName("More_Menu_Widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.More_Menu_Widget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.More_Menu_Frame = QtWidgets.QFrame(parent=self.More_Menu_Widget)
        self.More_Menu_Frame.setStyleSheet("padding:2px 3px;\n"
"background-color: rgb(45, 50, 61);\n"
"    border-radius: 8px; ")
        self.More_Menu_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.More_Menu_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.More_Menu_Frame.setObjectName("More_Menu_Frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.More_Menu_Frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.More_Menu_Label = QtWidgets.QLabel(parent=self.More_Menu_Frame)
        self.More_Menu_Label.setMinimumSize(QtCore.QSize(0, 15))
        self.More_Menu_Label.setMaximumSize(QtCore.QSize(80, 35))
        self.More_Menu_Label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.More_Menu_Label.setStyleSheet("border: rgb(255, 255, 255);\n"
"    text-align:center;\n"
"    padding:0px 2px;\n"
"    border-top-left-radius:8px;\n"
"    border-top-right-radius:8px;    \n"
"    border-bottom-left-radius:8px;\n"
"    border-bottom-right-radius:8px;")
        self.More_Menu_Label.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.More_Menu_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.More_Menu_Label.setObjectName("More_Menu_Label")
        self.horizontalLayout_3.addWidget(self.More_Menu_Label)
        self.More_Menu_close_Button = QtWidgets.QPushButton(parent=self.More_Menu_Frame)
        self.More_Menu_close_Button.setMaximumSize(QtCore.QSize(30, 16777215))
        self.More_Menu_close_Button.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.More_Menu_close_Button.setStyleSheet("border: rgb(255, 255, 255);")
        self.More_Menu_close_Button.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/Icons2/x-circle.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.More_Menu_close_Button.setIcon(icon10)
        self.More_Menu_close_Button.setCheckable(True)
        self.More_Menu_close_Button.setAutoExclusive(True)
        self.More_Menu_close_Button.setObjectName("More_Menu_close_Button")
        self.horizontalLayout_3.addWidget(self.More_Menu_close_Button)
        self.verticalLayout_8.addWidget(self.More_Menu_Frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.More_Menu_Stack_Frame = QtWidgets.QFrame(parent=self.More_Menu_Widget)
        self.More_Menu_Stack_Frame.setMinimumSize(QtCore.QSize(0, 400))
        self.More_Menu_Stack_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.More_Menu_Stack_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.More_Menu_Stack_Frame.setObjectName("More_Menu_Stack_Frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.More_Menu_Stack_Frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.More_Menu_Stacked_Widget = QtWidgets.QStackedWidget(parent=self.More_Menu_Stack_Frame)
        self.More_Menu_Stacked_Widget.setObjectName("More_Menu_Stacked_Widget")
        self.Settings_Page = QtWidgets.QWidget()
        self.Settings_Page.setObjectName("Settings_Page")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.Settings_Page)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Settings_Page_Label = QtWidgets.QLabel(parent=self.Settings_Page)
        self.Settings_Page_Label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.Settings_Page_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Settings_Page_Label.setObjectName("Settings_Page_Label")
        self.horizontalLayout_10.addWidget(self.Settings_Page_Label)
        self.More_Menu_Stacked_Widget.addWidget(self.Settings_Page)
        self.Information_Page = QtWidgets.QWidget()
        self.Information_Page.setObjectName("Information_Page")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.Information_Page)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Information_Page_Label = QtWidgets.QLabel(parent=self.Information_Page)
        self.Information_Page_Label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.Information_Page_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Information_Page_Label.setObjectName("Information_Page_Label")
        self.horizontalLayout_8.addWidget(self.Information_Page_Label)
        self.More_Menu_Stacked_Widget.addWidget(self.Information_Page)
        self.horizontalLayout_7.addWidget(self.More_Menu_Stacked_Widget)
        self.verticalLayout_8.addWidget(self.More_Menu_Stack_Frame)
        self.horizontalLayout.addWidget(self.More_Menu_Widget)
        self.Main_Body_Widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.Main_Body_Widget.setMinimumSize(QtCore.QSize(500, 450))
        self.Main_Body_Widget.setMaximumSize(QtCore.QSize(900, 16777215))
        self.Main_Body_Widget.setObjectName("Main_Body_Widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Main_Body_Widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Title_Widget = QtWidgets.QWidget(parent=self.Main_Body_Widget)
        self.Title_Widget.setMinimumSize(QtCore.QSize(0, 50))
        self.Title_Widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Title_Widget.setStyleSheet("*{background-color:#343B48;\n"
"border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;    \n"
"    border-bottom-left-radius:10px;\n"
"    border-bottom-right-radius:10px;}")
        self.Title_Widget.setObjectName("Title_Widget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.Title_Widget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame = QtWidgets.QFrame(parent=self.Title_Widget)
        self.frame.setMinimumSize(QtCore.QSize(220, 0))
        self.frame.setMaximumSize(QtCore.QSize(220, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.titleText_3 = QtWidgets.QTextEdit(parent=self.frame)
        self.titleText_3.setGeometry(QtCore.QRect(60, -10, 161, 41))
        self.titleText_3.setStyleSheet("color:#5479C4")
        self.titleText_3.setObjectName("titleText_3")
        self.logoButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.logoButton_3.setGeometry(QtCore.QRect(20, 0, 41, 31))
        self.logoButton_3.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/Icons2/images/Logofyp.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logoButton_3.setIcon(icon11)
        self.logoButton_3.setIconSize(QtCore.QSize(30, 30))
        self.logoButton_3.setObjectName("logoButton_3")
        self.horizontalLayout_13.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.frame_2 = QtWidgets.QFrame(parent=self.Title_Widget)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.minimizeButton_5 = QtWidgets.QPushButton(parent=self.frame_2)
        self.minimizeButton_5.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/Icons2/minus.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimizeButton_5.setIcon(icon12)
        self.minimizeButton_5.setObjectName("minimizeButton_5")
        self.horizontalLayout_15.addWidget(self.minimizeButton_5)
        self.restoreButton_5 = QtWidgets.QPushButton(parent=self.frame_2)
        self.restoreButton_5.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/Icons2/square.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.restoreButton_5.setIcon(icon13)
        self.restoreButton_5.setObjectName("restoreButton_5")
        self.horizontalLayout_15.addWidget(self.restoreButton_5)
        self.closeButton_5 = QtWidgets.QPushButton(parent=self.frame_2)
        self.closeButton_5.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/Icons2/x.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closeButton_5.setIcon(icon14)
        self.closeButton_5.setObjectName("closeButton_5")
        self.horizontalLayout_15.addWidget(self.closeButton_5)
        self.horizontalLayout_13.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.Title_Widget)
        self.Main_Body_Page_Stack = QtWidgets.QStackedWidget(parent=self.Main_Body_Widget)
        self.Main_Body_Page_Stack.setStyleSheet("background-color:#2C313C;")
        self.Main_Body_Page_Stack.setObjectName("Main_Body_Page_Stack")
        self.Home_Page = QtWidgets.QWidget()
        self.Home_Page.setObjectName("Home_Page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Home_Page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_3.addItem(spacerItem1)
        self.Start_Widget = QtWidgets.QWidget(parent=self.Home_Page)
        self.Start_Widget.setMinimumSize(QtCore.QSize(0, 80))
        self.Start_Widget.setStyleSheet("")
        self.Start_Widget.setObjectName("Start_Widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.Start_Widget)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.Start_Button_Frame = QtWidgets.QFrame(parent=self.Start_Widget)
        self.Start_Button_Frame.setMinimumSize(QtCore.QSize(300, 80))
        self.Start_Button_Frame.setMaximumSize(QtCore.QSize(400, 80))
        self.Start_Button_Frame.setStyleSheet("#Start_Button_Frame{\n"
"    border: 1px solid #AA1465;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"#QPushButton:checked{\n"
"    background-color:rgb(255, 220, 211) ;\n"
"}")
        self.Start_Button_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Start_Button_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Start_Button_Frame.setObjectName("Start_Button_Frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Start_Button_Frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Start_Text_Label = QtWidgets.QLabel(parent=self.Start_Button_Frame)
        self.Start_Text_Label.setStyleSheet("color: rgb(255, 255, 255);")
        self.Start_Text_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Start_Text_Label.setObjectName("Start_Text_Label")
        self.verticalLayout_2.addWidget(self.Start_Text_Label)
        self.Start_Button = QtWidgets.QPushButton(parent=self.Start_Button_Frame)
        self.Start_Button.setMinimumSize(QtCore.QSize(40, 20))
        self.Start_Button.setMaximumSize(QtCore.QSize(40, 16777215))
        self.Start_Button.setStyleSheet("background-color:rgb(170, 20, 101);\n"
"text-align:center;\n"
"padding:2px 10px;\n"
"    border-top-left-radius:6px;\n"
"    border-top-right-radius:6px;    \n"
"    border-bottom-left-radius:6px;\n"
"    border-bottom-right-radius:6px;\n"
"checked:rgb(255, 220, 211) ;")
        self.Start_Button.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/Icons2/power.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Start_Button.setIcon(icon15)
        self.Start_Button.setCheckable(True)
        self.Start_Button.setAutoExclusive(True)
        self.Start_Button.setObjectName("Start_Button")
        self.verticalLayout_2.addWidget(self.Start_Button, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_9.addWidget(self.Start_Button_Frame)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.Start_Widget)
        spacerItem4 = QtWidgets.QSpacerItem(20, 32, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_3.addItem(spacerItem4)
        self.Option_Button_Widget = QtWidgets.QWidget(parent=self.Home_Page)
        self.Option_Button_Widget.setMinimumSize(QtCore.QSize(0, 220))
        self.Option_Button_Widget.setMaximumSize(QtCore.QSize(16777215, 400))
        self.Option_Button_Widget.setStyleSheet("#QLabel{\n"
"color:#5479C4;\n"
"border: rgb(255, 255, 255);}\n"
"\n"
"#QPushButton{\n"
"color:#5479C4;\n"
"border: rgb(255, 255, 255);}\n"
"")
        self.Option_Button_Widget.setObjectName("Option_Button_Widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Option_Button_Widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Option_Button_Grid_Layout = QtWidgets.QGridLayout()
        self.Option_Button_Grid_Layout.setSpacing(15)
        self.Option_Button_Grid_Layout.setObjectName("Option_Button_Grid_Layout")
        self.Feedback_Frame = QtWidgets.QFrame(parent=self.Option_Button_Widget)
        self.Feedback_Frame.setMinimumSize(QtCore.QSize(0, 0))
        self.Feedback_Frame.setMaximumSize(QtCore.QSize(220, 130))
        self.Feedback_Frame.setStyleSheet("border: 1px solid #568AF2;\n"
"    border-radius: 8px; ")
        self.Feedback_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Feedback_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Feedback_Frame.setObjectName("Feedback_Frame")
        self.Feedback_Label = QtWidgets.QTextEdit(parent=self.Feedback_Frame)
        self.Feedback_Label.setGeometry(QtCore.QRect(60, 10, 111, 41))
        self.Feedback_Label.setStyleSheet("color:#5479C4;\n"
"border: rgb(255, 255, 255);")
        self.Feedback_Label.setObjectName("Feedback_Label")
        self.Feedback_Button = QtWidgets.QRadioButton(parent=self.Feedback_Frame)
        self.Feedback_Button.setGeometry(QtCore.QRect(50, 60, 131, 41))
        self.Feedback_Button.setStyleSheet("    color:#E5D9D9;\n"
"border: rgb(255, 255, 255);")
        self.Feedback_Button.setObjectName("Feedback_Button")
        self.Option_Button_Grid_Layout.addWidget(self.Feedback_Frame, 0, 1, 1, 1)
        self.Mode_Frame = QtWidgets.QFrame(parent=self.Option_Button_Widget)
        self.Mode_Frame.setMinimumSize(QtCore.QSize(220, 130))
        self.Mode_Frame.setMaximumSize(QtCore.QSize(220, 130))
        self.Mode_Frame.setStyleSheet("border: 1px solid #568AF2;\n"
"    border-radius: 8px; ")
        self.Mode_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Mode_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Mode_Frame.setObjectName("Mode_Frame")
        self.Auto_Mode_Button = QtWidgets.QRadioButton(parent=self.Mode_Frame)
        self.Auto_Mode_Button.setGeometry(QtCore.QRect(70, 60, 91, 16))
        self.Auto_Mode_Button.setStyleSheet("    color:#E5D9D9;\n"
"border: rgb(255, 255, 255);")
        self.Auto_Mode_Button.setObjectName("Auto_Mode_Button")
        self.Manual_Mode_Button = QtWidgets.QRadioButton(parent=self.Mode_Frame)
        self.Manual_Mode_Button.setGeometry(QtCore.QRect(70, 90, 93, 16))
        self.Manual_Mode_Button.setStyleSheet("    color:#E5D9D9;\n"
"border: rgb(255, 255, 255);")
        self.Manual_Mode_Button.setObjectName("Manual_Mode_Button")
        self.Select_Mode_Label = QtWidgets.QLabel(parent=self.Mode_Frame)
        self.Select_Mode_Label.setGeometry(QtCore.QRect(80, 20, 71, 20))
        self.Select_Mode_Label.setStyleSheet("color:#5479C4;\n"
"border: rgb(255, 255, 255);")
        self.Select_Mode_Label.setObjectName("Select_Mode_Label")
        self.Option_Button_Grid_Layout.addWidget(self.Mode_Frame, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Reset_First_Frame = QtWidgets.QFrame(parent=self.Option_Button_Widget)
        self.Reset_First_Frame.setMinimumSize(QtCore.QSize(0, 0))
        self.Reset_First_Frame.setMaximumSize(QtCore.QSize(220, 70))
        self.Reset_First_Frame.setStyleSheet("border: 1px solid #568AF2;\n"
"    border-radius: 8px; ")
        self.Reset_First_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Reset_First_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Reset_First_Frame.setObjectName("Reset_First_Frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.Reset_First_Frame)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Reset_First_Frame_Button = QtWidgets.QPushButton(parent=self.Reset_First_Frame)
        self.Reset_First_Frame_Button.setStyleSheet("color:#5479C4;\n"
"border: rgb(255, 255, 255);")
        self.Reset_First_Frame_Button.setCheckable(True)
        self.Reset_First_Frame_Button.setAutoExclusive(True)
        self.Reset_First_Frame_Button.setObjectName("Reset_First_Frame_Button")
        self.horizontalLayout_11.addWidget(self.Reset_First_Frame_Button)
        self.Option_Button_Grid_Layout.addWidget(self.Reset_First_Frame, 1, 0, 1, 1)
        self.Option_Button_Frame = QtWidgets.QFrame(parent=self.Option_Button_Widget)
        self.Option_Button_Frame.setMinimumSize(QtCore.QSize(0, 0))
        self.Option_Button_Frame.setMaximumSize(QtCore.QSize(220, 70))
        self.Option_Button_Frame.setStyleSheet(" \n"
"    border: 1px solid #568AF2;\n"
"    border-radius: 8px; \n"
"")
        self.Option_Button_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Option_Button_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Option_Button_Frame.setObjectName("Option_Button_Frame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.Option_Button_Frame)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Minimize_To_Tray_Button = QtWidgets.QPushButton(parent=self.Option_Button_Frame)
        self.Minimize_To_Tray_Button.setStyleSheet("color:#5479C4;\n"
"border: rgb(255, 255, 255);")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/Icons2/chevrons-down.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Minimize_To_Tray_Button.setIcon(icon16)
        self.Minimize_To_Tray_Button.setCheckable(True)
        self.Minimize_To_Tray_Button.setAutoExclusive(True)
        self.Minimize_To_Tray_Button.setObjectName("Minimize_To_Tray_Button")
        self.horizontalLayout_12.addWidget(self.Minimize_To_Tray_Button)
        self.Option_Button_Grid_Layout.addWidget(self.Option_Button_Frame, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.Option_Button_Grid_Layout, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.Option_Button_Widget)
        self.Main_Body_Page_Stack.addWidget(self.Home_Page)
        self.Manual_Page = QtWidgets.QWidget()
        self.Manual_Page.setObjectName("Manual_Page")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.Manual_Page)
        self.stackedWidget.setGeometry(QtCore.QRect(19, 9, 451, 391))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.Main_Body_Page_Stack.addWidget(self.Manual_Page)
        self.Gesture_Library_Page = QtWidgets.QWidget()
        self.Gesture_Library_Page.setObjectName("Gesture_Library_Page")
        self.Main_Body_Page_Stack.addWidget(self.Gesture_Library_Page)
        self.verticalLayout.addWidget(self.Main_Body_Page_Stack)
        self.horizontalLayout.addWidget(self.Main_Body_Widget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.More_Menu_Stacked_Widget.setCurrentIndex(1)
        self.Main_Body_Page_Stack.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(1)
        self.More_Menu_close_Button.clicked['bool'].connect(self.More_Menu_Widget.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Menu_Button.setText(_translate("MainWindow", "Menu"))
        self.Home_Button.setText(_translate("MainWindow", "Home"))
        self.Library_Button.setText(_translate("MainWindow", "Gesture Library"))
        self.pushButton.setText(_translate("MainWindow", "Applications"))
        self.pushButton_2.setText(_translate("MainWindow", "Gestures"))
        self.Manual_Button.setText(_translate("MainWindow", "Manual"))
        self.pushButton_3.setText(_translate("MainWindow", "Auto Mode"))
        self.pushButton_4.setText(_translate("MainWindow", "Manual Mode"))
        self.Information_Button.setText(_translate("MainWindow", "Information"))
        self.Settings_Button.setText(_translate("MainWindow", "Settings"))
        self.More_Menu_Label.setText(_translate("MainWindow", "More Menu"))
        self.Settings_Page_Label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Information</span></p></body></html>"))
        self.Settings_Page_Label.setText(_translate("MainWindow", "Information"))
        self.Information_Page_Label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Information</span></p></body></html>"))
        self.Information_Page_Label.setText(_translate("MainWindow", "Settings"))
        self.titleText_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700; font-style:italic;\">MotionPilot</span></p></body></html>"))
        self.Start_Text_Label.setText(_translate("MainWindow", "Start Application"))
        self.Feedback_Label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#5479c4;\">Feedback Gesture</span></p></body></html>"))
        self.Feedback_Button.setText(_translate("MainWindow", "Turn on feedback \n"
"gesture window"))
        self.Auto_Mode_Button.setText(_translate("MainWindow", "Auto Mode"))
        self.Manual_Mode_Button.setText(_translate("MainWindow", "Manual Mode"))
        self.Select_Mode_Label.setText(_translate("MainWindow", "Select Mode"))
        self.Reset_First_Frame_Button.setText(_translate("MainWindow", "Reset First Frame"))
        self.Minimize_To_Tray_Button.setText(_translate("MainWindow", "Minimize to tray"))
